# Completions Plugin - Functions
# Generates and installs tab-completion scripts for bash and zsh.
#
# Two workflows:
#   1. Metadata-driven: Parse the JSON metadata block embedded in scripts
#      built with the init wizard, then generate completions automatically.
#      Usage:  completions_generate /path/to/my-script.sh
#
#   2. Programmatic: Build completion definitions from argument arrays
#      passed directly by the init wizard during script creation.
#      Usage:  completions_from_args "scriptname" "bash" argArray
#
# Both produce shell-specific completion files that can be installed to
# standard directories with completions_install.

# ==============================================================================
# METADATA EXTRACTION
# ==============================================================================

# Extract the JSON metadata block from a script file
# Arguments:
#   $1 - Path to script file
# Returns: JSON string via stdout, or empty if not found
_comp_extract_metadata() {
    local scriptPath=$1

    if [[ ! -r "$scriptPath" ]]; then
        return 1
    fi

    # Extract lines between JSON_METADATA_START and JSON_METADATA_END,
    # strip leading comment markers, reassemble as JSON
    sed -n '/JSON_METADATA_START/,/JSON_METADATA_END/p' "$scriptPath" | \
        grep -v 'JSON_METADATA' | \
        sed 's/^#[[:space:]]*//' | \
        tr -d '\n'
}

# Extract argument names from a script's --help output
# Arguments:
#   $1 - Path to script file
# Returns: Space-separated long option names via stdout
_comp_extract_help_options() {
    local scriptPath=$1

    # Run --help and parse the options section
    "$scriptPath" --help 2>/dev/null | \
        grep -oE '\-\-[a-zA-Z][a-zA-Z0-9-]+' | \
        sort -u | \
        tr '\n' ' '
}

# ==============================================================================
# BASH COMPLETION GENERATION
# ==============================================================================

# Generate a bash completion script for a given command
# Arguments:
#   $1 - Command name (basename, no path)
#   $2 - Space-separated long options (e.g., "help version verbose config")
#   $3 - Space-separated short options (e.g., "h V v c")
#   $4 - Space-separated options that take file arguments (e.g., "config output")
#   $5 - Space-separated options that take directory arguments (optional)
# Returns: Bash completion script via stdout
completions_generate_bash() {
    local cmdName=$1
    local longOpts=${2:-""}
    local shortOpts=${3:-""}
    local fileOpts=${4:-""}
    local dirOpts=${5:-""}

    # Build the --long-options list
    local longOptList=""
    for opt in $longOpts; do
        longOptList="${longOptList} --${opt}"
    done

    # Build the -short list
    local shortOptList=""
    for opt in $shortOpts; do
        shortOptList="${shortOptList} -${opt}"
    done

    # Sanitize command name for use as function identifier
    local funcName="_${cmdName//[^a-zA-Z0-9_]/_}"

    cat <<BASHCOMP
# bash completion for ${cmdName}
# Generated by Shell Script Templates v4 completions plugin
#
# Installation:
#   User:   cp this-file ~/.local/share/bash-completion/completions/${cmdName}
#   System: sudo cp this-file /etc/bash_completion.d/${cmdName}
#   Manual: source this-file

${funcName}() {
    local cur prev opts
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    # All available options
    opts="${longOptList} ${shortOptList}"

    # Handle options that expect specific argument types
    case "\${prev}" in
BASHCOMP

    # Generate file-completion cases
    for opt in $fileOpts; do
        printf '        --%s)\n' "$opt"
        printf '            COMPREPLY=( $(compgen -f -- "\${cur}") )\n'
        printf '            return 0\n'
        printf '            ;;\n'
    done

    # Generate directory-completion cases
    for opt in $dirOpts; do
        printf '        --%s)\n' "$opt"
        printf '            COMPREPLY=( $(compgen -d -- "\${cur}") )\n'
        printf '            return 0\n'
        printf '            ;;\n'
    done

    cat <<'BASHCOMP2'
    esac

    # Complete options when current word starts with a dash
    if [[ "${cur}" == -* ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
        return 0
    fi

    # Default to file completion for positional arguments
    COMPREPLY=( $(compgen -f -- "${cur}") )
    return 0
}

BASHCOMP2

    printf 'complete -F %s %s\n' "$funcName" "$cmdName"
}

# ==============================================================================
# ZSH COMPLETION GENERATION
# ==============================================================================

# Generate a zsh completion function for a given command
# Arguments:
#   $1 - Command name (basename, no path)
#   $2 - Newline-separated argument definitions
#        Format per line: "short|long|type|required|description"
#        (Same format as init wizard CUSTOM_ARGS)
# Returns: Zsh completion function via stdout
completions_generate_zsh() {
    local cmdName=$1
    local argDefs=${2:-""}

    # Sanitize command name for function identifier
    local funcName="_${cmdName//[^a-zA-Z0-9_]/_}"

    cat <<ZSHCOMP
#compdef ${cmdName}
# zsh completion for ${cmdName}
# Generated by Shell Script Templates v4 completions plugin
#
# Installation:
#   Copy to a directory in your \$fpath, e.g.:
#     cp this-file ~/.zsh/completions/_${cmdName}
#   Then: autoload -Uz compinit && compinit

${funcName}() {
    local -a options
    options=(
        '(-h --help)'{-h,--help}'[Show help message and exit]'
        '(-V --version)'{-V,--version}'[Show version information and exit]'
        '*'{-v,--verbose}'[Increase verbosity (repeatable)]'
        '(-q --quiet)'{-q,--quiet}'[Suppress non-error output]'
        '(-n --dry-run)'{-n,--dry-run}'[Show what would be done without executing]'
        '(-d --debug)'{-d,--debug}'[Enable debug mode (maximum verbosity)]'
        '(-c --config)'{-c,--config}'[Configuration file]:config file:_files'
        '(-o --output)'{-o,--output}'[Output file]:output file:_files'
        '--self-test[Run internal self-tests and exit]'
ZSHCOMP

    # Add custom argument definitions
    if [[ -n "$argDefs" ]]; then
        local line
        while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            local IFS='|'
            local parts
            read -r shortOpt longOpt argType isRequired helpText <<< "$line"

            local zshSpec=""

            if [[ "$argType" == "boolean" ]]; then
                # Boolean flag
                if [[ -n "$shortOpt" ]]; then
                    zshSpec="'(-${shortOpt} --${longOpt})'{-${shortOpt},--${longOpt}}'[${helpText}]'"
                else
                    zshSpec="'--${longOpt}[${helpText}]'"
                fi
            else
                # Option with argument
                local actionSpec=":"
                case "$argType" in
                    file_readable|file_writable|path)
                        actionSpec=":file:_files" ;;
                    dir_readable|dir_writable)
                        actionSpec=":directory:_directories" ;;
                    executable)
                        actionSpec=":command:_commands" ;;
                    hostname)
                        actionSpec=":host:_hosts" ;;
                    *)
                        actionSpec=":${argType}:" ;;
                esac

                if [[ -n "$shortOpt" ]]; then
                    zshSpec="'(-${shortOpt} --${longOpt})'{-${shortOpt},--${longOpt}}'[${helpText}]${actionSpec}'"
                else
                    zshSpec="'--${longOpt}[${helpText}]${actionSpec}'"
                fi
            fi

            printf '        %s\n' "$zshSpec"
        done <<< "$argDefs"
    fi

    cat <<ZSHCOMP2
    )

    _arguments -s \$options '*:file:_files'
}

${funcName} "\$@"
ZSHCOMP2
}

# ==============================================================================
# AUTO-GENERATION FROM SCRIPTS
# ==============================================================================

# Generate completion files for an existing script by parsing its metadata
# or --help output. Creates both bash and zsh completions.
# Arguments:
#   $1 - Path to script file
#   $2 - Output directory (optional, default: alongside the script)
# Returns: 0 on success, writes completion files to output dir
completions_generate() {
    local scriptPath=$1
    local outputDir=${2:-$(dirname "$scriptPath")}
    local scriptName
    scriptName=$(basename "$scriptPath")
    scriptName="${scriptName%.sh}"
    scriptName="${scriptName%.zsh}"

    # Try metadata extraction first
    local metadata
    metadata=$(_comp_extract_metadata "$scriptPath")

    local longOpts=""
    local shortOpts=""
    local fileOpts=""

    if [[ -n "$metadata" ]] && command -v jq >/dev/null 2>&1; then
        if declare -f debug >/dev/null 2>&1; then
            debug "completions: Generating from JSON metadata"
        fi

        # Extract options from metadata (if custom args are stored there)
        # For now, fall through to --help parsing since metadata stores
        # flags and dependencies, not individual CLI arguments
    fi

    # Parse --help output to discover options
    if [[ -x "$scriptPath" ]]; then
        local helpOutput
        helpOutput=$("$scriptPath" --help 2>/dev/null || true)

        # Extract long options
        longOpts=$(echo "$helpOutput" | grep -oE '\-\-[a-zA-Z][a-zA-Z0-9-]+' | \
            sed 's/^--//' | sort -u | tr '\n' ' ')

        # Extract short options
        shortOpts=$(echo "$helpOutput" | grep -oE '\s-[a-zA-Z]\b' | \
            sed 's/.*-//' | sort -u | tr '\n' ' ')

        # Detect file-argument options (heuristic: mentions FILE, PATH, or _files)
        fileOpts=$(echo "$helpOutput" | grep -iE '\-\-[a-z].*FILE|PATH' | \
            grep -oE '\-\-[a-zA-Z][a-zA-Z0-9-]+' | sed 's/^--//' | tr '\n' ' ')
    else
        # Script not executable, use template defaults
        longOpts="help version verbose quiet dry-run debug config output self-test"
        shortOpts="h V v q n d c o"
        fileOpts="config output"
    fi

    # Generate bash completion
    local bashFile="${outputDir}/${scriptName}.bash-completion"
    completions_generate_bash "$scriptName" "$longOpts" "$shortOpts" "$fileOpts" > "$bashFile"

    if declare -f info >/dev/null 2>&1; then
        info "Generated bash completion: ${bashFile}"
    fi

    # Generate zsh completion
    local zshFile="${outputDir}/_${scriptName}"
    completions_generate_zsh "$scriptName" "" > "$zshFile"

    if declare -f info >/dev/null 2>&1; then
        info "Generated zsh completion: ${zshFile}"
    fi

    return 0
}

# Generate completions from an argument definition array (used by init wizard)
# Arguments:
#   $1 - Script name (without extension)
#   $2 - Target shell ("bash", "zsh", or "both")
#   $3 - Name of array variable containing arg defs (format: short|long|type|req|help)
#   $4 - Output directory
# Returns: 0 on success, writes completion files
completions_from_args() {
    local scriptName=$1
    local targetShell=$2
    local -n argArray=$3
    local outputDir=$4

    if [[ "$targetShell" == "bash" ]] || [[ "$targetShell" == "both" ]]; then
        # Build option lists from arg definitions
        local longOpts="help version verbose quiet dry-run debug config output self-test"
        local shortOpts="h V v q n d c o"
        local fileOpts="config output"

        for argDef in "${argArray[@]}"; do
            local IFS='|'
            read -r sOpt lOpt aType aReq aHelp <<< "$argDef"
            [[ -n "$lOpt" ]] && longOpts="${longOpts} ${lOpt}"
            [[ -n "$sOpt" ]] && shortOpts="${shortOpts} ${sOpt}"
            case "$aType" in
                file_readable|file_writable|path) fileOpts="${fileOpts} ${lOpt}" ;;
            esac
        done

        local bashFile="${outputDir}/${scriptName}.bash-completion"
        completions_generate_bash "$scriptName" "$longOpts" "$shortOpts" "$fileOpts" > "$bashFile"

        if declare -f info >/dev/null 2>&1; then
            info "Generated: ${bashFile}"
        fi
    fi

    if [[ "$targetShell" == "zsh" ]] || [[ "$targetShell" == "both" ]]; then
        # Build newline-separated arg defs for zsh generator
        local argDefs=""
        for argDef in "${argArray[@]}"; do
            argDefs="${argDefs}${argDef}\n"
        done

        local zshFile="${outputDir}/_${scriptName}"
        completions_generate_zsh "$scriptName" "$(printf '%b' "$argDefs")" > "$zshFile"

        if declare -f info >/dev/null 2>&1; then
            info "Generated: ${zshFile}"
        fi
    fi

    return 0
}

# ==============================================================================
# INSTALLATION AND MANAGEMENT
# ==============================================================================

# Install a completion file to the appropriate system/user directory
# Arguments:
#   $1 - Path to completion file
#   $2 - Target shell ("bash" or "zsh"; auto-detected from filename if omitted)
# Returns: 0 on success, 1 on failure
completions_install() {
    local compFile=$1
    local targetShell=${2:-""}
    local fileName
    fileName=$(basename "$compFile")

    # Auto-detect target shell from filename
    if [[ -z "$targetShell" ]]; then
        if [[ "$fileName" == _* ]]; then
            targetShell="zsh"
        elif [[ "$fileName" == *.bash-completion ]]; then
            targetShell="bash"
        else
            if declare -f error >/dev/null 2>&1; then
                error "completions_install: Cannot determine shell from filename '${fileName}'"
                error "  Use _name for zsh or name.bash-completion for bash"
            fi
            return 1
        fi
    fi

    local targetDir
    case "$targetShell" in
        bash) targetDir="$COMP_BASH_DIR" ;;
        zsh)  targetDir="$COMP_ZSH_DIR" ;;
        *)
            if declare -f error >/dev/null 2>&1; then
                error "completions_install: Unknown shell: ${targetShell}"
            fi
            return 1
            ;;
    esac

    # Create target directory if needed
    if [[ ! -d "$targetDir" ]]; then
        mkdir -p "$targetDir" 2>/dev/null || {
            if declare -f error >/dev/null 2>&1; then
                error "completions_install: Cannot create directory: ${targetDir}"
                error "  Try running with sudo or setting COMP_INSTALL_SCOPE=system"
            fi
            return 1
        }
    fi

    # Copy the completion file
    cp "$compFile" "${targetDir}/${fileName}" || {
        if declare -f error >/dev/null 2>&1; then
            error "completions_install: Failed to copy to ${targetDir}/${fileName}"
        fi
        return 1
    }

    if declare -f info >/dev/null 2>&1; then
        info "Installed ${targetShell} completion: ${targetDir}/${fileName}"
    fi

    # Provide reload instructions
    case "$targetShell" in
        bash)
            if declare -f info >/dev/null 2>&1; then
                info "  Reload: source ${targetDir}/${fileName}"
                info "  Or start a new shell session"
            fi
            ;;
        zsh)
            if declare -f info >/dev/null 2>&1; then
                info "  Reload: autoload -Uz compinit && compinit"
                info "  Or start a new shell session"
            fi
            ;;
    esac

    return 0
}

# Uninstall a completion file
# Arguments:
#   $1 - Command name (the script name, not the file)
#   $2 - Target shell ("bash", "zsh", or "both")
# Returns: 0 on success
completions_uninstall() {
    local cmdName=$1
    local targetShell=${2:-"both"}

    if [[ "$targetShell" == "bash" ]] || [[ "$targetShell" == "both" ]]; then
        local bashFile="${COMP_BASH_DIR}/${cmdName}.bash-completion"
        if [[ -f "$bashFile" ]]; then
            rm -f "$bashFile"
            if declare -f info >/dev/null 2>&1; then
                info "Removed bash completion: ${bashFile}"
            fi
        fi
    fi

    if [[ "$targetShell" == "zsh" ]] || [[ "$targetShell" == "both" ]]; then
        local zshFile="${COMP_ZSH_DIR}/_${cmdName}"
        if [[ -f "$zshFile" ]]; then
            rm -f "$zshFile"
            if declare -f info >/dev/null 2>&1; then
                info "Removed zsh completion: ${zshFile}"
            fi
        fi
    fi

    return 0
}

# List installed completions from this framework
# Arguments: None
# Returns: List of installed completions via stdout
completions_list() {
    local found=false

    if [[ -d "$COMP_BASH_DIR" ]]; then
        local bashFiles
        bashFiles=$(find "$COMP_BASH_DIR" -name '*.bash-completion' 2>/dev/null || true)
        if [[ -n "$bashFiles" ]]; then
            printf 'Bash completions (%s):\n' "$COMP_BASH_DIR"
            echo "$bashFiles" | while read -r f; do
                printf '  %s\n' "$(basename "$f")"
            done
            found=true
        fi
    fi

    if [[ -d "$COMP_ZSH_DIR" ]]; then
        local zshFiles
        zshFiles=$(find "$COMP_ZSH_DIR" -name '_*' -not -name '*.zwc' 2>/dev/null || true)
        if [[ -n "$zshFiles" ]]; then
            printf 'Zsh completions (%s):\n' "$COMP_ZSH_DIR"
            echo "$zshFiles" | while read -r f; do
                printf '  %s\n' "$(basename "$f")"
            done
            found=true
        fi
    fi

    if [[ "$found" == false ]]; then
        printf 'No completions installed.\n'
        printf '  Bash dir: %s\n' "$COMP_BASH_DIR"
        printf '  Zsh dir:  %s\n' "$COMP_ZSH_DIR"
    fi
}

# Print the detected completion directories
# Arguments: None
# Returns: None (prints to stdout)
completions_status() {
    printf 'Completions Plugin Status:\n'
    printf '  Shell:     %s\n' "$COMP_SHELL"
    printf '  Scope:     %s\n' "$COMP_INSTALL_SCOPE"
    printf '  Bash dir:  %s\n' "$COMP_BASH_DIR"
    printf '  Zsh dir:   %s\n' "$COMP_ZSH_DIR"
    printf '  Ready:     %s\n' "$COMP_READY"
}
